<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Philiprehberger.OptionType</PackageId>
    <Version>0.1.1</Version>
    <Authors>Philip Rehberger</Authors>
    <Description>Option/Maybe monad for explicit null handling with Map, Bind, Match, and LINQ support.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>option;maybe;monad;functional;null-handling</PackageTags>
    <RepositoryUrl>https://github.com/philiprehberger/dotnet-option-type</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
